language: node_js
node_js:
  - "4"
addons:
  firefox: "49.0"
  apt:
    packages:
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev
    - gfortran
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda2-4.2.12-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy=1.11.2 scipy=0.18.1
  - npm install
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - set -e
  - export PORT=8000
  - python -m CGIHTTPServer $PORT & sleep 1
  - python test.py
  - karma start --single-run --browsers Firefox
  - node_modules/.bin/eslint {js,test}/*
# Is this redundant?
# Travis checks package.json[scripts][test] for Node projects.
